//Owen Holloway 2013
//A change
//RSU Team-51

#define true 1
#define false 0

int running = 1;
int upTo = 0;

#include "headers/HelloWorld.h"

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#pragma config(Hubs,  S1, MatrxRbtcs, none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_Matrix_S1_1,  ,             tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_2,  ,             tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_3,  ,             tmotorMatrix, openLoop)
#pragma config(Motor,  mtr_Matrix_S1_4,  ,             tmotorMatrix, openLoop)

task main()
{
	StartTask(Hello);

	while(running) {
	}

}
